# Generated by Django 5.2.15 on 2026-06-04 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('verkaufspreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Verkaufspreis')),
                ('einheit', models.CharField(default='Stk.', max_length=20, verbose_name='Einheit')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(help_text='Anzeige z. B. PR10025', max_length=20, unique=True, verbose_name='Nummer')),
                ('titel', models.CharField(help_text='Adresse zur Identifikation im Tagebuch, z. B. Musterstraße 4, Dresden', max_length=200, verbose_name='Titel')),
                ('projekttyp', models.CharField(choices=[('Wärmepumpe', 'Wärmepumpe'), ('PV', 'PV'), ('Solarthermie', 'Solarthermie'), ('Bad', 'Bad')], default='Wärmepumpe', max_length=30, verbose_name='Projekttyp')),
                ('projektart', models.CharField(choices=[('Privatperson', 'Privatperson'), ('Großbaustelle', 'Großbaustelle')], default='Privatperson', max_length=20, verbose_name='Projektart')),
                ('status', models.CharField(choices=[('In Planung', 'In Planung'), ('In Bearbeitung', 'In Bearbeitung'), ('Abgeschlossen', 'Abgeschlossen')], default='In Planung', max_length=20, verbose_name='Status')),
                ('enddatum', models.DateField(verbose_name='Enddatum')),
                ('kostenvoranschlag', models.DecimalField(decimal_places=2, help_text='Budget (Soll-Kosten)', max_digits=12, verbose_name='Kostenvoranschlag')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['nummer'],
            },
        ),
        migrations.CreateModel(
            name='Monteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('projekte', models.ManyToManyField(blank=True, help_text='Fest zugeordnet; tageweiser Wechsel zwischen Projekten möglich.', related_name='monteure', to='shk.projekt', verbose_name='Projekte')),
            ],
            options={
                'verbose_name': 'Monteur',
                'verbose_name_plural': 'Monteure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Projekttagebuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('stunden', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Stunden')),
                ('text', models.TextField(blank=True, verbose_name='Fortschritts-Update')),
                ('monteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tagebuch_eintraege', to='shk.monteur', verbose_name='Monteur')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagebuch_eintraege', to='shk.projekt', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projekttagebuch-Eintrag',
                'verbose_name_plural': 'Projekttagebuch',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Materialposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Menge')),
                ('produkt', models.ForeignKey(help_text='Pflicht – zwingend auf ein Katalog-Produkt gemappt.', on_delete=django.db.models.deletion.PROTECT, related_name='materialpositionen', to='shk.produkt', verbose_name='Produkt')),
                ('eintrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialpositionen', to='shk.projekttagebuch', verbose_name='Tagebuch-Eintrag')),
            ],
            options={
                'verbose_name': 'Materialposition',
                'verbose_name_plural': 'Materialpositionen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Projektvorgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('soll_aufwand', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Soll-Aufwand (Stunden)')),
                ('enddatum', models.DateField(verbose_name='Enddatum')),
                ('status', models.CharField(choices=[('Geplant', 'Geplant'), ('In Bearbeitung', 'In Bearbeitung'), ('Abgeschlossen', 'Abgeschlossen')], default='Geplant', max_length=20, verbose_name='Status')),
                ('abgerechnet', models.BooleanField(default=False, verbose_name='Abgerechnet')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorgaenge', to='shk.projekt', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projektvorgang',
                'verbose_name_plural': 'Projektvorgänge',
                'ordering': ['enddatum'],
            },
        ),
        migrations.AddField(
            model_name='projekttagebuch',
            name='vorgang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagebuch_eintraege', to='shk.projektvorgang', verbose_name='Vorgang'),
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=30, unique=True, verbose_name='Rechnungsnummer')),
                ('betrag', models.DecimalField(decimal_places=2, help_text='Festgeschriebene Summe (Personal + Material)', max_digits=12, verbose_name='Betrag')),
                ('erstellt_am', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen', to='shk.projekt', verbose_name='Projekt')),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen', to='shk.projektvorgang', verbose_name='Vorgang')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
